---
- name: Create user group
  group:
    name: "{{ user_group }}"
  
- name: Create user
  user:
    name: "{{ username }}"
    group: "{{ user_group }}"
    shell: "/bin/bash"
    password: "{{ user_password }}"
    home: "/home/{{ username }}"
    createhome: yes

- name: Create ssh directory
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory

- name: Copy ssh_keys
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.ssh/{{ item }}"
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Add user to sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^rat'
    line: 'rat      ALL=(ALL:ALL) ALL'
