---
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - apvlv
    - ansible
    - wget
    - bind
    - firefox
    - feh
    - mpv
    - cron
    - bash-completion
    - termite
    - emacs
    - pavucontrol
    - dmenu
    - scrot
    - screenfetch
    - xclip
    - git
    - htop
    - pulseaudio
    - rtorrent
    - speedtest-cli
    - gimp
    - whois
    - awesome-terminal-fonts
    - xorg-xinit
    - slim
    - openssh
    - ttf-dejavu
