---
- name: Get bash configs from git
  git:
    repo: "https://github.com/Cuttlerat/bash_dump"
    dest: "/tmp/bash_configs"

- name: Copy bash_configs
  copy:
    src: "/tmp/bash_configs/Bashrc/{{ item }}"
    dest: "/home/{{ username }}/.{{ item }}"
  with_items:
    - bashrc
    - bash_aliases
    - bash_functions
    - bash_profile
    - bash_prompt
    - sshrc
    - inputrc
    
- name: Copy bin files
  copy:
    src: "/tmp/bash_configs/Everyday\ Scripts/"
    dest: "/usr/local/bin"

- name: Delete temp directory
  file:
    path: "/tmp/bash_configs"
    state: absent

- name: Copy x11 configs
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.{{ item }}"
  with_items:
    - Xauthority
    - xinitrc

- name: Ensure termite directory is exists
  file:
    path: "/home/{{ username }}/.config/termite"
    state: directory

- name: Copy termite config
  copy:
    src: "termite_config"
    dest: "/home/{{ username }}/.config/termite/config"

- name: Add monitor hotplug rule
  lineinfile:
    path: /etc/udev/rules.d/95-monitor.rules
    line: 'KERNEL=="card0", SUBSYSTEM=="drm", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/rat/.Xauthority", RUN+="/usr/local/bin/change_monitor"'
    regexp: '^KERNEL=="card0"'
    insertafter: EOF
    create: yes
    state: present
